### ISSUE TITLE
Update action to use Node.js 16 (or later) (Github deprecation warning)

### ISSUE THREAD

**Issue by vanGastelJS** [philips-software/inner-source-checkout-action#238]
Since yesterday, Github flags using this action with the following deprecation warning below:

`Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: philips-software/inner-source-checkout-action`

As our repository uses internal repositories as submodules, we depend on this action to (continue to) work.

**Comment by vanGastelJS** [comment]
Using the latest release (v1.2.1) I still receive this deprication warning. I noticed that the main branch is newer and changed from node12 to node16. However, no new release has been made with these updates.

@JeroenKnoops  @Brend-Smits 
 Could you make a release which includes the latest updates, at least with the update to node16?

**Comment by JeroenKnoops** [comment]
You're right. I will check and update some documentation and will make a release.
